[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_anch_elections = "GaQ54Jta5EcPTbizuNAA6Cq1DZbxUUVfhTJoHSzC8roF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
