[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_anch_elections = "GaQ54Jta5EcPTbizuNAA6Cq1DZbxUUVfhTJoHSzC8roF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "sleep 3 && cargo test"

[test]
startup_wait = 500

[test.validator]
reset = true
bind_address = "127.0.0.1"
rpc_port = 8899